### ISSUE TITLE
soft id doesnt work

### ISSUE THREAD

**Issue by median** [Furry/2captcha#35]
when putting soft id in the extra parameter it doesnt get applied

**Comment by Furry** [comment]
I appreciate you using my code for your project. Within the codebase, the 2captcha-ts wrapper soft_id parameter is hard coded into the project. 

https://github.dev/Furry/2captcha/blob/72a0f13648545925fa83dc4a862b637872a2685a/src/structs/2captcha.ts#L91 is where the parameter is hard coded. Feel free to modify this in your installed version to your own soft_id, the reason it's overridden is because if my code is used I kind of expect credit for my code being used..
